<?php

namespace AppBundle\Repository;

/**
 * ArtistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistaRepository extends \Doctrine\ORM\EntityRepository
{
}
